spring.application.name=pertemuan11

spring.datasource.url=jdbc:postgresql://localhost:5433/praktikum_db
spring.datasource.username=praktikum_user
spring.datasource.password=Df999999999999.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect